create table if not exists public.page_settings (
  id bigint generated by default as identity primary key,
  page text not null unique,
  title text not null,
  slug text not null unique,
  description text not null default '',
  keywords text not null default '',
  indexable boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id boolean primary key default true,
  site_name text not null default 'Snaiotech',
  logo_url text not null default '',
  favicon_url text not null default '',
  canonical_url text not null default '',
  default_description text not null default '',
  og_image_url text not null default '',
  instagram text not null default '',
  facebook text not null default '',
  linkedin text not null default '',
  email text not null default '',
  robots text not null default 'index, follow',
  schema_type text not null default 'ProfessionalService',
  updated_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  company text not null default '',
  service text not null default '',
  message text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.page_settings enable row level security;
alter table public.site_settings enable row level security;
alter table public.submissions enable row level security;

create policy "Public can read page settings" on public.page_settings for select using (true);
create policy "Admins manage page settings" on public.page_settings for all to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid())) with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
create policy "Public can read site settings" on public.site_settings for select using (true);
create policy "Admins manage site settings" on public.site_settings for all to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid())) with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
create policy "Anyone can submit contact form" on public.submissions for insert with check (true);
create policy "Admins read submissions" on public.submissions for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));
create policy "Admins update submissions" on public.submissions for update to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid())) with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

insert into public.page_settings (page, title, slug, description, keywords) values
('Home', 'Snaiotech - Digital Services Built to Dominate', '/', 'Digital services for modern businesses: web development, SEO, AEO, GEO, accessibility, and Zoho automation.', 'web development, SEO, AEO, GEO, Zoho, WCAG'),
('About', 'Who We Are - Snaiotech', '/about', 'Meet the team behind Snaiotech and our practical approach to digital growth.', 'Snaiotech, digital agency, Chennai'),
('Blog', 'Insights - Snaiotech', '/blog', 'Useful insights on search visibility, accessible documents, web development, and automation.', 'digital marketing insights, SEO blog'),
('Contact', 'Contact Snaiotech', '/contact', 'Start a conversation with Snaiotech about your next digital project.', 'contact Snaiotech, digital services')
on conflict (page) do nothing;

insert into public.site_settings (id, logo_url, canonical_url, default_description, instagram, facebook, linkedin, email)
values (true, 'https://res.cloudinary.com/piyrx4qi/image/upload/f_auto,q_auto/logo', 'https://snaiotech.com', 'Premium digital services for businesses that demand excellence.', 'https://www.instagram.com/snaiotech/', 'https://www.facebook.com/snaiotech', 'https://www.linkedin.com/in/snaiotech/', 'Info@snaiotech.com')
on conflict (id) do nothing;
