-- ============================================================
-- SNAiO Tech — Initial Supabase Schema
-- Safe to run on every deploy: uses IF NOT EXISTS + ON CONFLICT
-- ============================================================

-- ── Tables ──────────────────────────────────────────────────

create table if not exists public.page_settings (
  id          bigint generated by default as identity primary key,
  page        text not null unique,
  title       text not null default '',
  slug        text not null unique,
  description text not null default '',
  keywords    text not null default '',
  indexable   boolean not null default true,
  updated_at  timestamptz not null default now()
);

create table if not exists public.site_settings (
  id                  boolean primary key default true,
  site_name           text not null default 'Snaiotech',
  logo_url            text not null default '',
  favicon_url         text not null default '',
  canonical_url       text not null default 'https://snaiotech.com',
  default_description text not null default '',
  og_image_url        text not null default '',
  instagram           text not null default 'https://www.instagram.com/snaiotech/',
  facebook            text not null default 'https://www.facebook.com/snaiotech',
  linkedin            text not null default 'https://www.linkedin.com/in/snaiotech/',
  email               text not null default 'Info@snaiotech.com',
  robots              text not null default 'index, follow',
  schema_type         text not null default 'ProfessionalService',
  ga_id               text not null default '',
  gsc_verification    text not null default '',
  geo_region          text not null default 'IN-TN',
  geo_placename       text not null default 'Chennai, Tamil Nadu, India',
  geo_position        text not null default '13.0827;80.2707',
  updated_at          timestamptz not null default now()
);

create table if not exists public.submissions (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  email      text not null,
  company    text not null default '',
  service    text not null default '',
  message    text not null,
  status     text not null default 'new' check (status in ('new', 'contacted', 'archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- ── Add new columns to existing tables (idempotent) ─────────
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'site_settings' and column_name = 'ga_id') then
    alter table public.site_settings add column ga_id text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'site_settings' and column_name = 'gsc_verification') then
    alter table public.site_settings add column gsc_verification text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'site_settings' and column_name = 'geo_region') then
    alter table public.site_settings add column geo_region text not null default 'IN-TN';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'site_settings' and column_name = 'geo_placename') then
    alter table public.site_settings add column geo_placename text not null default 'Chennai, Tamil Nadu, India';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'site_settings' and column_name = 'geo_position') then
    alter table public.site_settings add column geo_position text not null default '13.0827;80.2707';
  end if;
end $$;

-- ── Row Level Security ───────────────────────────────────────
alter table public.page_settings enable row level security;
alter table public.site_settings enable row level security;
alter table public.submissions enable row level security;

-- Page settings policies
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'page_settings' and policyname = 'Public can read page settings') then
    create policy "Public can read page settings" on public.page_settings for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'page_settings' and policyname = 'Admins manage page settings') then
    create policy "Admins manage page settings" on public.page_settings for all to authenticated
      using (exists (select 1 from public.admin_users where user_id = auth.uid()))
      with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
  end if;
end $$;

-- Site settings policies
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'site_settings' and policyname = 'Public can read site settings') then
    create policy "Public can read site settings" on public.site_settings for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'site_settings' and policyname = 'Admins manage site settings') then
    create policy "Admins manage site settings" on public.site_settings for all to authenticated
      using (exists (select 1 from public.admin_users where user_id = auth.uid()))
      with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
  end if;
end $$;

-- Submissions policies
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'submissions' and policyname = 'Anyone can submit contact form') then
    create policy "Anyone can submit contact form" on public.submissions for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'submissions' and policyname = 'Admins read submissions') then
    create policy "Admins read submissions" on public.submissions for select to authenticated
      using (exists (select 1 from public.admin_users where user_id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where tablename = 'submissions' and policyname = 'Admins update submissions') then
    create policy "Admins update submissions" on public.submissions for update to authenticated
      using (exists (select 1 from public.admin_users where user_id = auth.uid()))
      with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
  end if;
end $$;

-- ── Seed data ────────────────────────────────────────────────
insert into public.page_settings (page, title, slug, description, keywords) values
  ('Home',    'Snaiotech — Digital Services Built to Dominate',  '/',        'Digital services for modern businesses: web development, SEO, AEO, GEO, accessibility, and Zoho automation.', 'web development, SEO, AEO, GEO, Zoho, WCAG, Chennai'),
  ('WebDev',  'Web Dev & SEO/AEO/GEO — Snaiotech',              '/webdev',  'Custom web development and search visibility services including traditional SEO, Answer Engine and Generative Engine Optimization.', 'web dev, SEO, AEO, GEO, generative engine optimization, Chennai'),
  ('PDF',     'PDF Accessibility & WCAG Compliance — Snaiotech', '/pdf',     'Professional PDF remediation, WCAG 2.2 compliance, and ADA Section 508 accessibility services.', 'PDF accessibility, WCAG 2.2, ADA, Section 508, remediation'),
  ('Zoho',    'Zoho Deployment & Customization — Snaiotech',     '/zoho',    'End-to-end Zoho CRM deployment, module customization, and business automation for growing teams.', 'Zoho CRM, Zoho deployment, CRM customization, business automation'),
  ('About',   'Who We Are — Snaiotech',                          '/about',   'Meet the team behind Snaiotech and our practical approach to digital growth for businesses worldwide.', 'Snaiotech, digital agency, Chennai, about us'),
  ('Blog',    'Insights — Snaiotech',                             '/blog',    'Useful insights on search visibility, accessible documents, web development, and automation.', 'digital marketing insights, SEO blog, AEO, GEO'),
  ('Contact', 'Contact Snaiotech',                               '/contact', 'Start a conversation with Snaiotech about your next digital project. Based in Chennai, serving clients globally.', 'contact Snaiotech, digital services, Chennai')
on conflict (page) do nothing;

insert into public.site_settings (
  id, site_name, logo_url, canonical_url, default_description,
  og_image_url, instagram, facebook, linkedin, email,
  robots, schema_type, geo_region, geo_placename, geo_position
) values (
  true,
  'Snaiotech',
  'https://res.cloudinary.com/piyrx4qi/image/upload/f_auto,q_auto/logo',
  'https://snaiotech.com',
  'Premium digital services for businesses that demand excellence — web development, SEO/AEO/GEO, PDF accessibility, and Zoho automation.',
  'https://res.cloudinary.com/piyrx4qi/image/upload/f_auto,q_auto/og-image',
  'https://www.instagram.com/snaiotech/',
  'https://www.facebook.com/snaiotech',
  'https://www.linkedin.com/in/snaiotech/',
  'Info@snaiotech.com',
  'index, follow',
  'ProfessionalService',
  'IN-TN',
  'Chennai, Tamil Nadu, India',
  '13.0827;80.2707'
) on conflict (id) do nothing;
